name: Julia Coverage
description: Process and submit coverage information from Julia.
author: https://github.com/maleadt
requirements: [julia, curl]
configuration:
  properties:
    codecov:
      type: boolean
    dirs:
      type: array
  additionalProperties: false
