name: Julia Coverage
description: Process and submit coverage information from a Julia test run.
author: https://github.com/maleadt
requirements: [julia]
configuration:
  properties:
  additionalProperties: false
