#!/bin/bash
set -euov pipefail

echo "--- :julia: Processing coverage"

julia --project -e 'using Pkg;
                    Pkg.add("Coverage");
                    using Coverage;
                    Codecov.submit(process_folder());'
