#!/bin/bash
set -euov pipefail

echo "--- :julia: Processing coverage"

julia --project -e 'using Pkg;
                    Pkg.activate("julia-coverage", shared=true);
                    Pkg.add(PackageSpec(name="CoverageTools"));
                    using CoverageTools;
                    pf = process_folder();
                    LCOV.writefile("lcov.info", pf)'
