#!/bin/bash
set -euov pipefail


echo "--- :julia: Processing coverage"

julia --project -e 'using Pkg;
                    Pkg.activate("julia-coverage", shared=true);
                    Pkg.add(PackageSpec(name="CoverageTools"));
                    using CoverageTools;
                    pf = process_folder();
                    LCOV.writefile("lcov.info", pf)'


codecov=${BUILDKITE_PLUGIN_JULIA_COVERAGE_CODECOV:-false}

if [ "$codecov" = true ] ; then
    echo "--- :codecov: Submitting to Codecov"

    # NOTE: we use the Bash uploader because
    #       Coverage.jl doesn't support Buildkite
    bash <(curl -s https://codecov.io/bash) -f lcov.info
fi
