#!/usr/bin/env bash
set -euo pipefail


echo "--- :julia: Processing coverage"

# parse the 'dirs' property
dirs=()
while IFS='=' read -r name _ ; do
  if [[ $name =~ ^(BUILDKITE_PLUGIN_JULIA_COVERAGE_DIRS_[0-9]+) ]] ; then
    dirs+=( "${!name}" )
  fi
done < <(env | sort)
if [ ${#dirs[@]} -eq 0 ]; then
    dirs+=( "src" )
fi

julia -e 'using Pkg
          Pkg.UPDATED_REGISTRY_THIS_SESSION[] = true
          Pkg.activate("julia-coverage", shared=true)
          Pkg.add(PackageSpec(name="Coverage", uuid="a2441757-f6aa-5fb2-8edb-039e3f45d037", version="1.4"))
          using Coverage
          pf = vcat(map(process_folder, ARGS)...)
          foreach(clean_folder, ARGS)
          Codecov.submit(pf)' "${dirs[@]}"
